### ISSUE TITLE
Class NgFormValidationMixin with add_djng_error attribute set to True

### ISSUE THREAD

**Issue by br0th3r** [jrief/django-angular#167] opened 2015-06-07 07:42 UTC
Hello:

I have been developing for a long time with **django-angular** and I just found a problem with one specific form.

The problem comes when I **POST** a form (normal form, **NOT** Model Form) to the server and the server, Django doesn't validate it, and send it back to the client, then the client get a normal error, and when it start typing in the input, the error message disappears (but the field stays invalid no matter what).

After a lot of debugging I found out that the class **NgFormValidationMixin** is setting an attribute "**add_djng_error**" to "**True**". I also checked out that this attribute is set to "**False**" on "Model Forms".

This attribute is adding to the resulting HTML code (**NOT** in Model Forms) an attribute to the field named: **djng-error="bound-field"**

I also have tested when I set "**add_djng_error**" to "**False**" the form is working as expected.

Checking the full source code I see:
- client/src/js/ng-django-forms.js: element.removeAttr('djng-error');
- djangular/static/djangular/js/django-angular.js: element.removeAttr('djng-error');
- djangular/forms/widgets.py: attrs.pop('djng-error', None)
- djangular/forms/widgets.py: attrs.pop('djng-error', None)
- djangular/forms/angular_validation.py: attrs.update({'djng-error': 'bound-field'})

Then I went throught "**ng-django-form.js**" and checked that the directive "**djngError**" is responsible for turning bound fields from valid to invalid (on pristine) and then back to valid.

The questions are:
- What is the attribute "add_djng_error" for?
- Why the form is working properly when I set it to False in a normal form (NOT Model Form)?

Thank you,

**Comment by jrief** [comment] 2015-06-07 19:57
Thanks for this detailed bug report.
Could you please modify the example code, and create a branch in your fork of the repository, so that I can reproduce it. I currently don't really understand what's happening.
Jacob

**Comment by adrienbrunet** [comment] 2017-09-20 07:09
My best guess is that it is fixed now. The issue is quite old and a lot have changed.

**Closed by adrienbrunet** 2017-09-20 07:09 UTC
