### ISSUE TITLE
New request attributes in DjangularUrlMiddleware 

### ISSUE THREAD

**Issue by null-none** [jrief/django-angular#223] opened 2016-01-03 21:29 UTC
After creating `new_request` in djangular/middleware.py, attributes user and session (at least) are lost. A new request is created and these attributes are dropped.
We should kept user and session for correct use (especially with multiple middlewares).
```
new_request = WSGIRequest(request.environ)
```

**Comment by adrienbrunet** [comment] 2016-01-03 23:23
I'm really sorry but I don't understand your problem. Can you describe it along with your use case more precisely? Maybe you can even provide a reproductible error/environment for us to work on? I really can't help you out with the information you provided. It makes no sens to me.

What are you trying to achieve? What have you already done? What is the error you have? Have you followed the documentation? etc...

Cheers!

**Comment by adrienbrunet** [comment] 2016-01-03 23:30
I commented your related issue. Could you provide a test or a bit of documentation? Maybe this can help some other folks. Cheers. I haven't encountered such problem with that middleware yet.

**Comment by null-none** [comment] 2016-01-04 06:13
Example [mezzanine] (http://mezzanine.jupo.org/) have many middlewares when use request.user and request.session. Current django-angular use [middleware] (https://github.com/jrief/django-angular/blob/master/djangular/middleware.py) recreates request but without request.user and request.session. Understand?

**Comment by adrienbrunet** [comment] 2016-01-04 08:30
I commented on your PR. Tests are failing right now. This can't be merged.

**Comment by jkosir** [comment] 2016-01-04 11:00
Well the middleware in fact does remove session and user data, along with some other attributes I suppose. Not sure how this went unnoticed for so long. Will be fixed asap.

**Comment by adrienbrunet** [comment] 2016-01-04 12:43
:+1:

**Comment by jkosir** [comment] 2016-01-04 13:49
Well actually user and session attributes are added in Session and Authenticaton middlewares. So if you use DjangularMiddleware correctly (first in MIDDLEWARE_CLASSES - that's what you are doing wrong) everyting works properly.

Either way I'd merge the new version of request building, since it's more robust and future-proof. Also I added code to remove djng_url_kwargs from query string.

**Closed** 2016-01-05 11:29 UTC
